package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Txt generated by hbm2java
 */
public class Txt  implements java.io.Serializable {


     private BigDecimal codigo;
     private String descripcion;
     private Set<Subtxt> subtxts = new HashSet<Subtxt>(0);

    public Txt() {
    }

	
    public Txt(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Txt(BigDecimal codigo, String descripcion, Set<Subtxt> subtxts) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.subtxts = subtxts;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Subtxt> getSubtxts() {
        return this.subtxts;
    }
    
    public void setSubtxts(Set<Subtxt> subtxts) {
        this.subtxts = subtxts;
    }




}


