package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Serie generated by hbm2java
 */
public class Serie  implements java.io.Serializable {


     private BigDecimal idserie;
     private String codigo;
     private String descripcion;
     private BigDecimal anyo;
     private BigDecimal contador;
     private String baja;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Serie() {
    }

	
    public Serie(BigDecimal idserie, BigDecimal anyo) {
        this.idserie = idserie;
        this.anyo = anyo;
    }
    public Serie(BigDecimal idserie, String codigo, String descripcion, BigDecimal anyo, BigDecimal contador, String baja, Set<Cliente> clientes) {
       this.idserie = idserie;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.anyo = anyo;
       this.contador = contador;
       this.baja = baja;
       this.clientes = clientes;
    }
   
    public BigDecimal getIdserie() {
        return this.idserie;
    }
    
    public void setIdserie(BigDecimal idserie) {
        this.idserie = idserie;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getAnyo() {
        return this.anyo;
    }
    
    public void setAnyo(BigDecimal anyo) {
        this.anyo = anyo;
    }
    public BigDecimal getContador() {
        return this.contador;
    }
    
    public void setContador(BigDecimal contador) {
        this.contador = contador;
    }
    public String getBaja() {
        return this.baja;
    }
    
    public void setBaja(String baja) {
        this.baja = baja;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


