package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Modelos generated by hbm2java
 */
public class Modelos  implements java.io.Serializable {


     private BigDecimal idmodelo;
     private Marcas marcas;
     private String modelo;
     private String baja;
     private Set<Infasegurado> infAsegurado = new HashSet<Infasegurado>(0);
     private Set<InfContrario> infContrario = new HashSet<InfContrario>(0);

    public Modelos() {
    }

	
    public Modelos(BigDecimal idmodelo, Marcas marcas, String modelo) {
        this.idmodelo = idmodelo;
        this.marcas = marcas;
        this.modelo = modelo;
    }
    public Modelos(BigDecimal idmodelo, Marcas marcas, String modelo, String baja, Set<Infasegurado> infAsegurado, Set<InfContrario> infContrario) {
       this.idmodelo = idmodelo;
       this.marcas = marcas;
       this.modelo = modelo;
       this.baja = baja;
       this.infAsegurado = infAsegurado;
       this.infContrario = infContrario;
    }
   
    public BigDecimal getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(BigDecimal idmodelo) {
        this.idmodelo = idmodelo;
    }
    public Marcas getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getBaja() {
        return this.baja;
    }
    
    public void setBaja(String baja) {
        this.baja = baja;
    }
      public Set<Infasegurado> getInfasegurado() {
        return this.infAsegurado;
    }
    
    public void setInfasegurado(Set<Infasegurado> infAsegurado) {
        this.infAsegurado = infAsegurado;
    }
public Set<InfContrario> getInfContrario() {
        return this.infContrario;
    }
    
    public void setInfContrario(Set<InfContrario> infContrario) {
        this.infContrario = infContrario;
    }





}


