package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Honorarios generated by hbm2java
 */
public class Honorarios  implements java.io.Serializable {


     private BigDecimal idhonorario;
     private Tarifa tarifa;
     private BigDecimal tramo;
     private BigDecimal honorario;
     private BigDecimal porcentajeexceso;
     private BigDecimal sobreexcesode;
     private BigDecimal minimo;
     private BigDecimal maximo;

    public Honorarios() {
    }

	
    public Honorarios(BigDecimal idhonorario, Tarifa tarifa) {
        this.idhonorario = idhonorario;
        this.tarifa = tarifa;
    }
    public Honorarios(BigDecimal idhonorario, Tarifa tarifa, BigDecimal tramo, BigDecimal honorario, BigDecimal porcentajeexceso, BigDecimal sobreexcesode, BigDecimal minimo, BigDecimal maximo) {
       this.idhonorario = idhonorario;
       this.tarifa = tarifa;
       this.tramo = tramo;
       this.honorario = honorario;
       this.porcentajeexceso = porcentajeexceso;
       this.sobreexcesode = sobreexcesode;
       this.minimo = minimo;
       this.maximo = maximo;
    }
   
    public BigDecimal getIdhonorario() {
        return this.idhonorario;
    }
    
    public void setIdhonorario(BigDecimal idhonorario) {
        this.idhonorario = idhonorario;
    }
    public Tarifa getTarifa() {
        return this.tarifa;
    }
    
    public void setTarifa(Tarifa tarifa) {
        this.tarifa = tarifa;
    }
    public BigDecimal getTramo() {
        return this.tramo;
    }
    
    public void setTramo(BigDecimal tramo) {
        this.tramo = tramo;
    }
    public BigDecimal getHonorario() {
        return this.honorario;
    }
    
    public void setHonorario(BigDecimal honorario) {
        this.honorario = honorario;
    }
    public BigDecimal getPorcentajeexceso() {
        return this.porcentajeexceso;
    }
    
    public void setPorcentajeexceso(BigDecimal porcentajeexceso) {
        this.porcentajeexceso = porcentajeexceso;
    }
    public BigDecimal getSobreexcesode() {
        return this.sobreexcesode;
    }
    
    public void setSobreexcesode(BigDecimal sobreexcesode) {
        this.sobreexcesode = sobreexcesode;
    }
    public BigDecimal getMinimo() {
        return this.minimo;
    }
    
    public void setMinimo(BigDecimal minimo) {
        this.minimo = minimo;
    }
    public BigDecimal getMaximo() {
        return this.maximo;
    }
    
    public void setMaximo(BigDecimal maximo) {
        this.maximo = maximo;
    }




}


