package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TramosKm generated by hbm2java
 */
public class TramosKm  implements java.io.Serializable {


     private BigDecimal idtramokm;
     private Tarifa tarifa;
     private BigDecimal tramo;
     private BigDecimal importetramo;
     private BigDecimal porcentajeexceso;
     private BigDecimal sobreexcesode;

    public TramosKm() {
    }

	
    public TramosKm(BigDecimal idtramokm, Tarifa tarifa) {
        this.idtramokm = idtramokm;
        this.tarifa = tarifa;
    }
    public TramosKm(BigDecimal idtramokm, Tarifa tarifa, BigDecimal tramo, BigDecimal importetramo, BigDecimal porcentajeexceso, BigDecimal sobreexcesode) {
       this.idtramokm = idtramokm;
       this.tarifa = tarifa;
       this.tramo = tramo;
       this.importetramo = importetramo;
       this.porcentajeexceso = porcentajeexceso;
       this.sobreexcesode = sobreexcesode;
    }
   
    public BigDecimal getIdtramokm() {
        return this.idtramokm;
    }
    
    public void setIdtramokm(BigDecimal idtramokm) {
        this.idtramokm = idtramokm;
    }
    public Tarifa getTarifa() {
        return this.tarifa;
    }
    
    public void setTarifa(Tarifa tarifa) {
        this.tarifa = tarifa;
    }
    public BigDecimal getTramo() {
        return this.tramo;
    }
    
    public void setTramo(BigDecimal tramo) {
        this.tramo = tramo;
    }
    public BigDecimal getImportetramo() {
        return this.importetramo;
    }
    
    public void setImportetramo(BigDecimal importetramo) {
        this.importetramo = importetramo;
    }
    public BigDecimal getPorcentajeexceso() {
        return this.porcentajeexceso;
    }
    
    public void setPorcentajeexceso(BigDecimal porcentajeexceso) {
        this.porcentajeexceso = porcentajeexceso;
    }
    public BigDecimal getSobreexcesode() {
        return this.sobreexcesode;
    }
    
    public void setSobreexcesode(BigDecimal sobreexcesode) {
        this.sobreexcesode = sobreexcesode;
    }




}


