package modelsMaestros;
// Generated 30-sep-2013 14:08:20 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Contador generated by hbm2java
 */
public class Contador  implements java.io.Serializable {


     private ContadorId id;
     private Ejercicio ejercicio;
     private Series series;
     private BigDecimal contador;

    public Contador() {
    }

    public Contador(ContadorId id, Ejercicio ejercicio, Series series, BigDecimal contador) {
       this.id = id;
       this.ejercicio = ejercicio;
       this.series = series;
       this.contador = contador;
    }
   
    public ContadorId getId() {
        return this.id;
    }
    
    public void setId(ContadorId id) {
        this.id = id;
    }
    public Ejercicio getEjercicio() {
        return this.ejercicio;
    }
    
    public void setEjercicio(Ejercicio ejercicio) {
        this.ejercicio = ejercicio;
    }
    public Series getSeries() {
        return this.series;
    }
    
    public void setSeries(Series series) {
        this.series = series;
    }
    public BigDecimal getContador() {
        return this.contador;
    }
    
    public void setContador(BigDecimal contador) {
        this.contador = contador;
    }




}


