package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private String idprovincia;
     private String provincia;
   //  private Set<Poblacion> poblacions = new HashSet<Poblacion>(0);

    public Provincia() {
    }

	
    public Provincia(String idprovincia) {
        this.idprovincia = idprovincia;
    }
    public Provincia(String idprovincia, String provincia){//, Set<Poblacion> poblacions) {
       this.idprovincia = idprovincia;
       this.provincia = provincia;
      // this.poblacions = poblacions;
    }
   
    public String getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(String idprovincia) {
        this.idprovincia = idprovincia;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
 /*   public Set<Poblacion> getPoblacions() {
        return this.poblacions;
    }
    
    public void setPoblacions(Set<Poblacion> poblacions) {
        this.poblacions = poblacions;
    }
*/



}


