package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private BigDecimal codrol;
     private String desrol;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Roles() {
    }

	
    public Roles(BigDecimal codrol) {
        this.codrol = codrol;
    }
    public Roles(BigDecimal codrol, String desrol, Set<Usuario> usuarios) {
       this.codrol = codrol;
       this.desrol = desrol;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getCodrol() {
        return this.codrol;
    }
    
    public void setCodrol(BigDecimal codrol) {
        this.codrol = codrol;
    }
    public String getDesrol() {
        return this.desrol;
    }
    
    public void setDesrol(String desrol) {
        this.desrol = desrol;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


