package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private BigDecimal idestado;
     private String tipo;
     private String codigo;
     private String descripcion;
     private String baja;

       private Set<InfInforme> InfInforme = new HashSet<InfInforme>(0);
    public Estados() {
    }

	
    public Estados(BigDecimal idestado) {
        this.idestado = idestado;
    }
    public Estados(BigDecimal idestado,String tipo, String codigo, String descripcion, String baja) {
       this.idestado = idestado;
       
       this.tipo = tipo;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.baja = baja;
    }
   
    public BigDecimal getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(BigDecimal idestado) {
        this.idestado = idestado;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getBaja() {
        return this.baja;
    }
    
    public void setBaja(String baja) {
        this.baja = baja;
    }

public Set<InfInforme> getInfInforme() {
        return this.InfInforme;
    }
    
    public void setInfInforme(Set<InfInforme> InfInforme) {
        this.InfInforme = InfInforme;
    }
@Override
    public final String toString ()
    {   
        return descripcion;
    }

}


