package modelsMaestros;
// Generated 30-sep-2013 14:08:20 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Perito generated by hbm2java
 */
public class Perito  implements java.io.Serializable {


     private BigDecimal idperito;
     private String perito;
     private String codigoPostal;
     private String telefono1;
     private String telefono2;
     private String email;
     private String comentario;
     private String nif;
     private BigDecimal irpf;
     private BigDecimal iva;
     private BigDecimal resultante;
     private BigDecimal fijo;
     private BigDecimal precioKm;
     private String cochePropio;
     private String fotos;
     private Date fechaAlta;
     private String baja;
     private String idpoblacion;
     private String idprovincia;

    

    public Perito() {
    }

	
    public Perito(BigDecimal idperito, String idpoblacion, String idprovincia) {
        this.idperito = idperito;
        this.idpoblacion = idpoblacion;
        this.idprovincia=idprovincia;
    }
    public Perito(BigDecimal idperito, String perito, String codigoPostal, String telefono1, String telefono2, String email, String comentario, String nif, BigDecimal irpf, BigDecimal iva, BigDecimal resultante, BigDecimal fijo, BigDecimal precioKm, String cochePropio, String fotos, Date fechaAlta, String baja, String idpoblacion, String idprovincia) {
       this.idperito = idperito;
       this.perito = perito;
       this.codigoPostal = codigoPostal;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.email = email;
       this.comentario = comentario;
       this.nif = nif;
       this.irpf = irpf;
       this.iva = iva;
       this.resultante = resultante;
       this.fijo = fijo;
       this.precioKm = precioKm;
       this.cochePropio = cochePropio;
       this.fotos = fotos;
       this.fechaAlta = fechaAlta;
       this.baja = baja;
       this.idpoblacion = idpoblacion;
       this.idprovincia = idprovincia;
    }
   
    public BigDecimal getIdperito() {
        return this.idperito;
    }
    
    public void setIdperito(BigDecimal idperito) {
        this.idperito = idperito;
    }
    public String getPerito() {
        return this.perito;
    }
    
    public void setPerito(String perito) {
        this.perito = perito;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public BigDecimal getIrpf() {
        return this.irpf;
    }
    
    public void setIrpf(BigDecimal irpf) {
        this.irpf = irpf;
    }
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }
    public BigDecimal getResultante() {
        return this.resultante;
    }
    
    public void setResultante(BigDecimal resultante) {
        this.resultante = resultante;
    }
    public BigDecimal getFijo() {
        return this.fijo;
    }
    
    public void setFijo(BigDecimal fijo) {
        this.fijo = fijo;
    }
    public BigDecimal getPrecioKm() {
        return this.precioKm;
    }
    
    public void setPrecioKm(BigDecimal precioKm) {
        this.precioKm = precioKm;
    }
    public String getCochePropio() {
        return this.cochePropio;
    }
    
    public void setCochePropio(String cochePropio) {
        this.cochePropio = cochePropio;
    }
    public String getFotos() {
        return this.fotos;
    }
    
    public void setFotos(String fotos) {
        this.fotos = fotos;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getBaja() {
        return this.baja;
    }
    
    public void setBaja(String baja) {
        this.baja = baja;
    }
    public String getIdpoblacion() {
        return this.idpoblacion;
    }
    
    public void setIdpoblacion(String idpoblacion) {
        this.idpoblacion = idpoblacion;
    }

public String getIdprovincia() {
        return idprovincia;
    }

    public void setIdprovincia(String idprovincia) {
        this.idprovincia = idprovincia;
    }

 @Override
    public final String toString ()
    {   
        return perito;
    }
}


