package models;
// Generated 20-may-2013 12:56:30 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * InfAvances generated by hbm2java
 */
public class InfAvances  implements java.io.Serializable {


     private BigDecimal idinfavance;
     private InfInforme infInforme;
     private String texto;
     private String textoCia;

   
     private String fechaavance;

    public InfAvances() {
    }

    public InfAvances(BigDecimal idinfavance, InfInforme infInforme, String texto, String fechaavance) {
       this.idinfavance = idinfavance;
       this.infInforme = infInforme;
       this.texto = texto;
       this.fechaavance = fechaavance;
    }
   
    public BigDecimal getIdinfavance() {
        return this.idinfavance;
    }
    
    public void setIdinfavance(BigDecimal idinfavance) {
        this.idinfavance = idinfavance;
    }
    public InfInforme getInfInforme() {
        return this.infInforme;
    }
    
    public void setInfInforme(InfInforme infInforme) {
        this.infInforme = infInforme;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public String getFechaavance() {
        return this.fechaavance;
    }
    
    public void setFechaavance(String fechaavance) {
        this.fechaavance = fechaavance;
    }

 public String getTextoCia() {
        return textoCia;
    }

    public void setTextoCia(String textoCia) {
        this.textoCia = textoCia;
    }


}


