package models;
// Generated 27-may-2013 14:26:49 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ClienteTextoAvance generated by hbm2java
 */
public class ClienteTextoAvance  implements java.io.Serializable {


     private BigDecimal idclientetextoavance;
    /* private BigDecimal idtextoavance;

    public BigDecimal getIdtextoavance() {
        return idtextoavance;
    }

    public void setIdtextoavance(BigDecimal idtextoavance) {
        this.idtextoavance = idtextoavance;
    }*/
     private TextoAvance textoAvance;
     private Cliente cliente;

    public ClienteTextoAvance() {
    }

    public ClienteTextoAvance(BigDecimal idclientetextoavance, TextoAvance textoAvance, Cliente cliente) {
       this.idclientetextoavance = idclientetextoavance;
       this.textoAvance = textoAvance;
       this.cliente = cliente;
    }
   
    public BigDecimal getIdclientetextoavance() {
        return this.idclientetextoavance;
    }
    
    public void setIdclientetextoavance(BigDecimal idclientetextoavance) {
        this.idclientetextoavance = idclientetextoavance;
    }
    public TextoAvance getTextoAvance() {
        return this.textoAvance;
    }
    
    public void setTextoAvance(TextoAvance textoAvance) {
        this.textoAvance = textoAvance;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }




}


