package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupotaller generated by hbm2java
 */
public class Grupotaller  implements java.io.Serializable {


     private BigDecimal idgrupotaller;
     private String denominacion;
     private String login;
     private String baja;
     private Set<Taller> tallers = new HashSet<Taller>(0);

    public Grupotaller() {
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

	
    public Grupotaller(BigDecimal idgrupotaller, String denominacion, String login) {
        this.idgrupotaller = idgrupotaller;
        this.denominacion = denominacion;
        this.login = login;
    }
    public Grupotaller(BigDecimal idgrupotaller, String denominacion, String baja, Set<Taller> tallers, String login) {
       this.idgrupotaller = idgrupotaller;
       this.denominacion = denominacion;
       this.baja = baja;
       this.tallers = tallers;
       this.login=login;
    }
   
    public BigDecimal getIdgrupotaller() {
        return this.idgrupotaller;
    }
    
    public void setIdgrupotaller(BigDecimal idgrupotaller) {
        this.idgrupotaller = idgrupotaller;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getBaja() {
        return this.baja;
    }
    
    public void setBaja(String baja) {
        this.baja = baja;
    }
    public Set<Taller> getTallers() {
        return this.tallers;
    }
    
    public void setTallers(Set<Taller> tallers) {
        this.tallers = tallers;
    }




}


