package models;
// Generated 21-nov-2013 12:41:03 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * InfDocinfinspeccionriesgo generated by hbm2java
 */
public class InfDocinfinspeccionriesgo  implements java.io.Serializable {


     private BigDecimal idinforme;
     private InfInforme infInforme;
     private Date fecha;
     private String estadogeneral;
     private String pintura;
     private String guarnecidos;
     private String oxidaciones;
     private String abolladuras;
     private String corrosiones;
     private String instalacionelectrica;
     private String neumaticosdelanteros;
     private String neumaticostraseros;
     private String descripciondanyos;
     private String descripcionaccesorios;
     private String observaciones;
     private String resumen;

    public InfDocinfinspeccionriesgo() {
    }

	
    public InfDocinfinspeccionriesgo(InfInforme infInforme) {
        this.infInforme = infInforme;
    }
    public InfDocinfinspeccionriesgo(InfInforme infInforme, Date fecha, String estadogeneral, String pintura, String guarnecidos, String oxidaciones, String abolladuras, String corrosiones, String instalacionelectrica, String neumaticosdelanteros, String neumaticostraseros, String descripciondanyos, String descripcionaccesorios, String observaciones, String resumen) {
       this.infInforme = infInforme;
       this.fecha = fecha;
       this.estadogeneral = estadogeneral;
       this.pintura = pintura;
       this.guarnecidos = guarnecidos;
       this.oxidaciones = oxidaciones;
       this.abolladuras = abolladuras;
       this.corrosiones = corrosiones;
       this.instalacionelectrica = instalacionelectrica;
       this.neumaticosdelanteros = neumaticosdelanteros;
       this.neumaticostraseros = neumaticostraseros;
       this.descripciondanyos = descripciondanyos;
       this.descripcionaccesorios = descripcionaccesorios;
       this.observaciones = observaciones;
       this.resumen = resumen;
    }
   
    public BigDecimal getIdinforme() {
        return this.idinforme;
    }
    
    public void setIdinforme(BigDecimal idinforme) {
        this.idinforme = idinforme;
    }
    public InfInforme getInfInforme() {
        return this.infInforme;
    }
    
    public void setInfInforme(InfInforme infInforme) {
        this.infInforme = infInforme;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstadogeneral() {
        return this.estadogeneral;
    }
    
    public void setEstadogeneral(String estadogeneral) {
        this.estadogeneral = estadogeneral;
    }
    public String getPintura() {
        return this.pintura;
    }
    
    public void setPintura(String pintura) {
        this.pintura = pintura;
    }
    public String getGuarnecidos() {
        return this.guarnecidos;
    }
    
    public void setGuarnecidos(String guarnecidos) {
        this.guarnecidos = guarnecidos;
    }
    public String getOxidaciones() {
        return this.oxidaciones;
    }
    
    public void setOxidaciones(String oxidaciones) {
        this.oxidaciones = oxidaciones;
    }
    public String getAbolladuras() {
        return this.abolladuras;
    }
    
    public void setAbolladuras(String abolladuras) {
        this.abolladuras = abolladuras;
    }
    public String getCorrosiones() {
        return this.corrosiones;
    }
    
    public void setCorrosiones(String corrosiones) {
        this.corrosiones = corrosiones;
    }
    public String getInstalacionelectrica() {
        return this.instalacionelectrica;
    }
    
    public void setInstalacionelectrica(String instalacionelectrica) {
        this.instalacionelectrica = instalacionelectrica;
    }
    public String getNeumaticosdelanteros() {
        return this.neumaticosdelanteros;
    }
    
    public void setNeumaticosdelanteros(String neumaticosdelanteros) {
        this.neumaticosdelanteros = neumaticosdelanteros;
    }
    public String getNeumaticostraseros() {
        return this.neumaticostraseros;
    }
    
    public void setNeumaticostraseros(String neumaticostraseros) {
        this.neumaticostraseros = neumaticostraseros;
    }
    public String getDescripciondanyos() {
        return this.descripciondanyos;
    }
    
    public void setDescripciondanyos(String descripciondanyos) {
        this.descripciondanyos = descripciondanyos;
    }
    public String getDescripcionaccesorios() {
        return this.descripcionaccesorios;
    }
    
    public void setDescripcionaccesorios(String descripcionaccesorios) {
        this.descripcionaccesorios = descripcionaccesorios;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }




}


