package models;
// Generated 21-nov-2013 12:41:03 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * InfDocinformevarios generated by hbm2java
 */
public class InfDocinformevarios  implements java.io.Serializable {


     private BigDecimal idinforme;
     private InfInforme infInforme;
     private String texto;
     private String observaciones;
     private Date fecha;
    //  private String fecha;

    public InfDocinformevarios() {
    }

	
    public InfDocinformevarios(InfInforme infInforme) {
        this.infInforme = infInforme;
    }
    public InfDocinformevarios(InfInforme infInforme, String texto, String observaciones, Date fecha) {
       this.infInforme = infInforme;
       this.texto = texto;
       this.observaciones = observaciones;
       this.fecha = fecha;
    }
   
    public BigDecimal getIdinforme() {
        return this.idinforme;
    }
    
    public void setIdinforme(BigDecimal idinforme) {
        this.idinforme = idinforme;
    }
    public InfInforme getInfInforme() {
        return this.infInforme;
    }
    
    public void setInfInforme(InfInforme infInforme) {
        this.infInforme = infInforme;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


