package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
/*import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
*/
/**
 * Taller generated by hbm2java
 */
/*@ManagedBean (name="taller")
@SessionScoped*/
public class Taller  implements java.io.Serializable {


     private BigDecimal idtaller;
     private Grupotaller grupotaller;
     private String nombre;
     private String denominacion;
     private String cif;
     private String direccion;
     private BigDecimal cp;
     private String tfno1;
     private String tfno2;
     private String fax;
     private String email;
     private String cuenta;
     private String avisos;
     //private BigDecimal tipotaller;
     private BigDecimal distanciaGabinete;
     private BigDecimal precioHora;
     private Date fechaAlta;
     private String idpoblacion;
 //    private Poblacion poblacion;
     private String provinciaTXT;

    private String poblacionTXT;

   

   // private String idpoblacion;
     private String idprovincia;
     private String baja;
     private int v;

   
     
     
    public Taller() {
    }

	
    public Taller(BigDecimal idtaller, String idpoblacion, String idprovincia) {
        this.idtaller = idtaller;
        this.idpoblacion = idpoblacion;
        this.idprovincia = idprovincia;
    }
    public Taller(BigDecimal idtaller, Grupotaller grupotaller, String nombre, String denominacion, String cif, String direccion, BigDecimal cp, String tfno1, String tfno2, String fax, String email, String cuenta, String avisos, BigDecimal distanciaGabinete, BigDecimal precioHora, Date fechaAlta, String idpoblacion, String idprovincia, String baja, int v) {
       this.idtaller = idtaller;
       this.grupotaller = grupotaller;
       this.nombre = nombre;
       this.denominacion = denominacion;
       this.cif = cif;
       this.direccion = direccion;
       this.cp = cp;
       this.tfno1 = tfno1;
       this.tfno2 = tfno2;
       this.fax = fax;
       this.email = email;
       this.cuenta = cuenta;
       this.avisos = avisos;
       //this.tipotaller = tipotaller;
       this.distanciaGabinete = distanciaGabinete;
       this.precioHora = precioHora;
       this.fechaAlta = fechaAlta;
       this.idpoblacion = idpoblacion;
       this.idprovincia = idprovincia;
       this.baja = baja;
       this.v=v;
    }
   
    public BigDecimal getIdtaller() {
        return this.idtaller;
    }
    
    public void setIdtaller(BigDecimal idtaller) {
        this.idtaller = idtaller;
    }
    public Grupotaller getGrupotaller() {
        return this.grupotaller;
    }
    
    public void setGrupotaller(Grupotaller grupotaller) {
        this.grupotaller = grupotaller;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getCp() {
        return this.cp;
    }
    
    public void setCp(BigDecimal cp) {
        this.cp = cp;
    }
    public String getTfno1() {
        return this.tfno1;
    }
    
    public void setTfno1(String tfno1) {
        this.tfno1 = tfno1;
    }
    public String getTfno2() {
        return this.tfno2;
    }
    
    public void setTfno2(String tfno2) {
        this.tfno2 = tfno2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public String getAvisos() {
        return this.avisos;
    }
    
    public void setAvisos(String avisos) {
        this.avisos = avisos;
    }
   /* public BigDecimal getTipotaller() {
        return this.tipotaller;
    }
    
    public void setTipotaller(BigDecimal tipotaller) {
        this.tipotaller = tipotaller;
    }*/
    public BigDecimal getDistanciaGabinete() {
        return this.distanciaGabinete;
    }
    
    public void setDistanciaGabinete(BigDecimal distanciaGabinete) {
        this.distanciaGabinete = distanciaGabinete;
    }
    public BigDecimal getPrecioHora() {
        return this.precioHora;
    }
    
    public void setPrecioHora(BigDecimal precioHora) {
        this.precioHora = precioHora;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getIdpoblacion() {
        return this.idpoblacion;
    }
    
    public void setIdpoblacion(String idpoblacion) {
        this.idpoblacion = idpoblacion;
    }
    public String getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(String idprovincia) {
        this.idprovincia = idprovincia;
    }
    public String getBaja() {
        return this.baja;
    }
    
    public void setBaja(String baja) {
        this.baja = baja;
    }

  public String getProvinciaTXT() {
        return provinciaTXT;
    }

    public void setProvinciaTXT(String provinciaTXT) {
        this.provinciaTXT = provinciaTXT;
    }
    public String getPoblacionTXT() {
        return poblacionTXT;
    }

    public void setPoblacionTXT(String poblacionTXT) {
        this.poblacionTXT = poblacionTXT;
    }
    
     public int getV() {
        return v;
    }

    public void setV(int v) {
        this.v = v;
    }

}


