package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipovehiculo generated by hbm2java
 */
public class Tipovehiculo  implements java.io.Serializable {


     private BigDecimal idtipovehiculo;
     private String descripcion;
     private Set<Infasegurado> infasegurado = new HashSet<Infasegurado>(0);
     private Set<InfContrario> infContrario = new HashSet<InfContrario>(0);

    public Tipovehiculo() {
    }

	
    public Tipovehiculo(BigDecimal idtipovehiculo) {
        this.idtipovehiculo = idtipovehiculo;
    }
    public Tipovehiculo(BigDecimal idtipovehiculo, String descripcion, Set<Infasegurado> infAsegurado, Set<InfContrario> infContrario) {
       this.idtipovehiculo = idtipovehiculo;
       this.descripcion = descripcion;
       this.infasegurado = infAsegurado;
       this.infContrario = infContrario;
    }
   
    public BigDecimal getIdtipovehiculo() {
        return this.idtipovehiculo;
    }
    
    public void setIdtipovehiculo(BigDecimal idtipovehiculo) {
        this.idtipovehiculo = idtipovehiculo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
  public Set<Infasegurado> getInfasegurado() {
        return this.infasegurado;
    }
    
    public void setInfasegurado(Set<Infasegurado> infAsegurado) {
        this.infasegurado = infAsegurado;
    }
public Set<InfContrario> getInfContrario() {
        return this.infContrario;
    }
    
    public void setInfContrario(Set<InfContrario> infContrario) {
        this.infContrario = infContrario;
    }





}


