package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
@ManagedBean (name="Tipoinforme")
@SessionScoped
/**
 * Tipoinforme generated by hbm2java
 */
public class Tipoinforme  implements java.io.Serializable {


     private BigDecimal idtipoinforme;
     private String descripcion;
     private Set<InfInforme> infInformes = new HashSet<InfInforme>(0);

    public Tipoinforme() {
    }

	
    public Tipoinforme(BigDecimal idtipoinforme, String descripcion) {
        this.idtipoinforme = idtipoinforme;
        this.descripcion = descripcion;
    }
    public Tipoinforme(BigDecimal idtipoinforme, String descripcion, Set<InfInforme> infInformes) {
       this.idtipoinforme = idtipoinforme;
       this.descripcion = descripcion;
       this.infInformes = infInformes;
    }
   
    public BigDecimal getIdtipoinforme() {
        return this.idtipoinforme;
    }
    
    public void setIdtipoinforme(BigDecimal idtipoinforme) {
        this.idtipoinforme = idtipoinforme;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<InfInforme> getInfInformes() {
        return this.infInformes;
    }
    
    public void setInfInformes(Set<InfInforme> infInformes) {
        this.infInformes = infInformes;
    }




}


