package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ZonasPeritoId generated by hbm2java
 */
public class ZonasPeritoId  implements java.io.Serializable {


     private BigDecimal idzona;
     private BigDecimal idperito;

    public ZonasPeritoId() {
    }

    public ZonasPeritoId(BigDecimal idzona, BigDecimal idperito) {
       this.idzona = idzona;
       this.idperito = idperito;
    }
   
    public BigDecimal getIdzona() {
        return this.idzona;
    }
    
    public void setIdzona(BigDecimal idzona) {
        this.idzona = idzona;
    }
    public BigDecimal getIdperito() {
        return this.idperito;
    }
    
    public void setIdperito(BigDecimal idperito) {
        this.idperito = idperito;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ZonasPeritoId) ) return false;
		 ZonasPeritoId castOther = ( ZonasPeritoId ) other; 
         
		 return ( (this.getIdzona()==castOther.getIdzona()) || ( this.getIdzona()!=null && castOther.getIdzona()!=null && this.getIdzona().equals(castOther.getIdzona()) ) )
 && ( (this.getIdperito()==castOther.getIdperito()) || ( this.getIdperito()!=null && castOther.getIdperito()!=null && this.getIdperito().equals(castOther.getIdperito()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdzona() == null ? 0 : this.getIdzona().hashCode() );
         result = 37 * result + ( getIdperito() == null ? 0 : this.getIdperito().hashCode() );
         return result;
   }   


}


