package models;
import modelsMaestros.Perito;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA



/**
 * ZonasPerito generated by hbm2java
 */
public class ZonasPerito  implements java.io.Serializable {


     private ZonasPeritoId id;
     private Perito perito;
     private String zona;

    public ZonasPerito() {
    }

	
    public ZonasPerito(ZonasPeritoId id, Perito perito) {
        this.id = id;
        this.perito = perito;
    }
    public ZonasPerito(ZonasPeritoId id, Perito perito, String zona) {
       this.id = id;
       this.perito = perito;
       this.zona = zona;
    }
   
    public ZonasPeritoId getId() {
        return this.id;
    }
    
    public void setId(ZonasPeritoId id) {
        this.id = id;
    }
    public Perito getPerito() {
        return this.perito;
    }
    
    public void setPerito(Perito perito) {
        this.perito = perito;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }




}


