package models;
// Generated 01-feb-2013 22:02:51 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarifa generated by hbm2java
 */
public class Tarifa  implements java.io.Serializable {


     private BigDecimal idtarifa;
     private String nombre;
     private BigDecimal visfallida;
     private BigDecimal sintotalsin;
     private BigDecimal sintotalvalsin;
     private BigDecimal sintotalvalsinmin;
     private BigDecimal sintotalvalsinmax;
     private BigDecimal sintotalvalcon;
     private BigDecimal sintotalvalconmin;
     private BigDecimal sintotalvalconmax;
     private BigDecimal veriflugar;
     private BigDecimal verifunidad;
     private BigDecimal inspeccion;
     private BigDecimal comprobdanos;
     private BigDecimal comprobfactura;
     private BigDecimal comprobaveria;
     private BigDecimal asistenciajuicio;
     private BigDecimal visseguimiento;
     private BigDecimal honormin;
     private BigDecimal asisjuiciofuera;
     private BigDecimal informetecnico;
     private BigDecimal revislda;
     private BigDecimal previorecons;
     private BigDecimal discrepaseg;
     private BigDecimal peritlunas;
     private BigDecimal impmaxfotos;
     private BigDecimal audatexman;
     private BigDecimal audatexproc;
     private BigDecimal gtestimate;
     private BigDecimal manual;
     private BigDecimal desplazamiento;
     private BigDecimal limite;
     private String tramokm;
     private String tramofoto;
     private BigDecimal importefotos;
     private BigDecimal importefotosmax;
     private BigDecimal importefotosmin;
     private BigDecimal limiteHonorarios;
     private Set<Honorarios> honorarioses = new HashSet<Honorarios>(0);
     private Set<FotosTarifa> fotosTarifas = new HashSet<FotosTarifa>(0);
     private Set<TramosKm> tramosKms = new HashSet<TramosKm>(0);

    public Tarifa() {
    }

	
    public Tarifa(BigDecimal idtarifa) {
        this.idtarifa = idtarifa;
    }
    public Tarifa(BigDecimal idtarifa, String nombre, BigDecimal visfallida, BigDecimal sintotalsin, BigDecimal sintotalvalsin, BigDecimal sintotalvalsinmin, BigDecimal sintotalvalsinmax, BigDecimal sintotalvalcon, BigDecimal sintotalvalconmin, BigDecimal sintotalvalconmax, BigDecimal veriflugar, BigDecimal verifunidad, BigDecimal inspeccion, BigDecimal comprobdanos, BigDecimal comprobfactura, BigDecimal comprobaveria, BigDecimal asistenciajuicio, BigDecimal visseguimiento, BigDecimal honormin, BigDecimal asisjuiciofuera, BigDecimal informetecnico, BigDecimal revislda, BigDecimal previorecons, BigDecimal discrepaseg, BigDecimal peritlunas, BigDecimal impmaxfotos, BigDecimal audatexman, BigDecimal audatexproc, BigDecimal gtestimate, BigDecimal manual, BigDecimal desplazamiento, BigDecimal limite, String tramokm, String tramofoto, BigDecimal importefotos, BigDecimal importefotosmax, BigDecimal importefotosmin, BigDecimal limiteHonorarios, Set<Honorarios> honorarioses, Set<FotosTarifa> fotosTarifas, Set<TramosKm> tramosKms) {
       this.idtarifa = idtarifa;
       this.nombre = nombre;
       this.visfallida = visfallida;
       this.sintotalsin = sintotalsin;
       this.sintotalvalsin = sintotalvalsin;
       this.sintotalvalsinmin = sintotalvalsinmin;
       this.sintotalvalsinmax = sintotalvalsinmax;
       this.sintotalvalcon = sintotalvalcon;
       this.sintotalvalconmin = sintotalvalconmin;
       this.sintotalvalconmax = sintotalvalconmax;
       this.veriflugar = veriflugar;
       this.verifunidad = verifunidad;
       this.inspeccion = inspeccion;
       this.comprobdanos = comprobdanos;
       this.comprobfactura = comprobfactura;
       this.comprobaveria = comprobaveria;
       this.asistenciajuicio = asistenciajuicio;
       this.visseguimiento = visseguimiento;
       this.honormin = honormin;
       this.asisjuiciofuera = asisjuiciofuera;
       this.informetecnico = informetecnico;
       this.revislda = revislda;
       this.previorecons = previorecons;
       this.discrepaseg = discrepaseg;
       this.peritlunas = peritlunas;
       this.impmaxfotos = impmaxfotos;
       this.audatexman = audatexman;
       this.audatexproc = audatexproc;
       this.gtestimate = gtestimate;
       this.manual = manual;
       this.desplazamiento = desplazamiento;
       this.limite = limite;
       this.tramokm = tramokm;
       this.tramofoto = tramofoto;
       this.importefotos = importefotos;
       this.importefotosmax = importefotosmax;
       this.importefotosmin = importefotosmin;
       this.limiteHonorarios = limiteHonorarios;
       this.honorarioses = honorarioses;
       this.fotosTarifas = fotosTarifas;
       this.tramosKms = tramosKms;
    }
   
    public BigDecimal getIdtarifa() {
        return this.idtarifa;
    }
    
    public void setIdtarifa(BigDecimal idtarifa) {
        this.idtarifa = idtarifa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getVisfallida() {
        return this.visfallida;
    }
    
    public void setVisfallida(BigDecimal visfallida) {
        this.visfallida = visfallida;
    }
    public BigDecimal getSintotalsin() {
        return this.sintotalsin;
    }
    
    public void setSintotalsin(BigDecimal sintotalsin) {
        this.sintotalsin = sintotalsin;
    }
    public BigDecimal getSintotalvalsin() {
        return this.sintotalvalsin;
    }
    
    public void setSintotalvalsin(BigDecimal sintotalvalsin) {
        this.sintotalvalsin = sintotalvalsin;
    }
    public BigDecimal getSintotalvalsinmin() {
        return this.sintotalvalsinmin;
    }
    
    public void setSintotalvalsinmin(BigDecimal sintotalvalsinmin) {
        this.sintotalvalsinmin = sintotalvalsinmin;
    }
    public BigDecimal getSintotalvalsinmax() {
        return this.sintotalvalsinmax;
    }
    
    public void setSintotalvalsinmax(BigDecimal sintotalvalsinmax) {
        this.sintotalvalsinmax = sintotalvalsinmax;
    }
    public BigDecimal getSintotalvalcon() {
        return this.sintotalvalcon;
    }
    
    public void setSintotalvalcon(BigDecimal sintotalvalcon) {
        this.sintotalvalcon = sintotalvalcon;
    }
    public BigDecimal getSintotalvalconmin() {
        return this.sintotalvalconmin;
    }
    
    public void setSintotalvalconmin(BigDecimal sintotalvalconmin) {
        this.sintotalvalconmin = sintotalvalconmin;
    }
    public BigDecimal getSintotalvalconmax() {
        return this.sintotalvalconmax;
    }
    
    public void setSintotalvalconmax(BigDecimal sintotalvalconmax) {
        this.sintotalvalconmax = sintotalvalconmax;
    }
    public BigDecimal getVeriflugar() {
        return this.veriflugar;
    }
    
    public void setVeriflugar(BigDecimal veriflugar) {
        this.veriflugar = veriflugar;
    }
    public BigDecimal getVerifunidad() {
        return this.verifunidad;
    }
    
    public void setVerifunidad(BigDecimal verifunidad) {
        this.verifunidad = verifunidad;
    }
    public BigDecimal getInspeccion() {
        return this.inspeccion;
    }
    
    public void setInspeccion(BigDecimal inspeccion) {
        this.inspeccion = inspeccion;
    }
    public BigDecimal getComprobdanos() {
        return this.comprobdanos;
    }
    
    public void setComprobdanos(BigDecimal comprobdanos) {
        this.comprobdanos = comprobdanos;
    }
    public BigDecimal getComprobfactura() {
        return this.comprobfactura;
    }
    
    public void setComprobfactura(BigDecimal comprobfactura) {
        this.comprobfactura = comprobfactura;
    }
    public BigDecimal getComprobaveria() {
        return this.comprobaveria;
    }
    
    public void setComprobaveria(BigDecimal comprobaveria) {
        this.comprobaveria = comprobaveria;
    }
    public BigDecimal getAsistenciajuicio() {
        return this.asistenciajuicio;
    }
    
    public void setAsistenciajuicio(BigDecimal asistenciajuicio) {
        this.asistenciajuicio = asistenciajuicio;
    }
    public BigDecimal getVisseguimiento() {
        return this.visseguimiento;
    }
    
    public void setVisseguimiento(BigDecimal visseguimiento) {
        this.visseguimiento = visseguimiento;
    }
    public BigDecimal getHonormin() {
        return this.honormin;
    }
    
    public void setHonormin(BigDecimal honormin) {
        this.honormin = honormin;
    }
    public BigDecimal getAsisjuiciofuera() {
        return this.asisjuiciofuera;
    }
    
    public void setAsisjuiciofuera(BigDecimal asisjuiciofuera) {
        this.asisjuiciofuera = asisjuiciofuera;
    }
    public BigDecimal getInformetecnico() {
        return this.informetecnico;
    }
    
    public void setInformetecnico(BigDecimal informetecnico) {
        this.informetecnico = informetecnico;
    }
    public BigDecimal getRevislda() {
        return this.revislda;
    }
    
    public void setRevislda(BigDecimal revislda) {
        this.revislda = revislda;
    }
    public BigDecimal getPreviorecons() {
        return this.previorecons;
    }
    
    public void setPreviorecons(BigDecimal previorecons) {
        this.previorecons = previorecons;
    }
    public BigDecimal getDiscrepaseg() {
        return this.discrepaseg;
    }
    
    public void setDiscrepaseg(BigDecimal discrepaseg) {
        this.discrepaseg = discrepaseg;
    }
    public BigDecimal getPeritlunas() {
        return this.peritlunas;
    }
    
    public void setPeritlunas(BigDecimal peritlunas) {
        this.peritlunas = peritlunas;
    }
    public BigDecimal getImpmaxfotos() {
        return this.impmaxfotos;
    }
    
    public void setImpmaxfotos(BigDecimal impmaxfotos) {
        this.impmaxfotos = impmaxfotos;
    }
    public BigDecimal getAudatexman() {
        return this.audatexman;
    }
    
    public void setAudatexman(BigDecimal audatexman) {
        this.audatexman = audatexman;
    }
    public BigDecimal getAudatexproc() {
        return this.audatexproc;
    }
    
    public void setAudatexproc(BigDecimal audatexproc) {
        this.audatexproc = audatexproc;
    }
    public BigDecimal getGtestimate() {
        return this.gtestimate;
    }
    
    public void setGtestimate(BigDecimal gtestimate) {
        this.gtestimate = gtestimate;
    }
    public BigDecimal getManual() {
        return this.manual;
    }
    
    public void setManual(BigDecimal manual) {
        this.manual = manual;
    }
    public BigDecimal getDesplazamiento() {
        return this.desplazamiento;
    }
    
    public void setDesplazamiento(BigDecimal desplazamiento) {
        this.desplazamiento = desplazamiento;
    }
    public BigDecimal getLimite() {
        return this.limite;
    }
    
    public void setLimite(BigDecimal limite) {
        this.limite = limite;
    }
    public String getTramokm() {
        return this.tramokm;
    }
    
    public void setTramokm(String tramokm) {
        this.tramokm = tramokm;
    }
    public String getTramofoto() {
        return this.tramofoto;
    }
    
    public void setTramofoto(String tramofoto) {
        this.tramofoto = tramofoto;
    }
    public BigDecimal getImportefotos() {
        return this.importefotos;
    }
    
    public void setImportefotos(BigDecimal importefotos) {
        this.importefotos = importefotos;
    }
    public BigDecimal getImportefotosmax() {
        return this.importefotosmax;
    }
    
    public void setImportefotosmax(BigDecimal importefotosmax) {
        this.importefotosmax = importefotosmax;
    }
    public BigDecimal getImportefotosmin() {
        return this.importefotosmin;
    }
    
    public void setImportefotosmin(BigDecimal importefotosmin) {
        this.importefotosmin = importefotosmin;
    }
    public BigDecimal getLimiteHonorarios() {
        return this.limiteHonorarios;
    }
    
    public void setLimiteHonorarios(BigDecimal limiteHonorarios) {
        this.limiteHonorarios = limiteHonorarios;
    }
    public Set<Honorarios> getHonorarioses() {
        return this.honorarioses;
    }
    
    public void setHonorarioses(Set<Honorarios> honorarioses) {
        this.honorarioses = honorarioses;
    }
    public Set<FotosTarifa> getFotosTarifas() {
        return this.fotosTarifas;
    }
    
    public void setFotosTarifas(Set<FotosTarifa> fotosTarifas) {
        this.fotosTarifas = fotosTarifas;
    }
    public Set<TramosKm> getTramosKms() {
        return this.tramosKms;
    }
    
    public void setTramosKms(Set<TramosKm> tramosKms) {
        this.tramosKms = tramosKms;
    }




}


