package modelsMaestros;
// Generated 30-sep-2013 14:08:20 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Ejercicio generated by hbm2java
 */
public class Ejercicio  implements java.io.Serializable {


     private BigDecimal idejercicio;
     private BigDecimal ejercicio;
     private String activo;
     private Set<Contador> contadors = new HashSet<Contador>(0);

    public Ejercicio() {
    }

	
    public Ejercicio(BigDecimal idejercicio) {
        this.idejercicio = idejercicio;
    }
    public Ejercicio(BigDecimal idejercicio, BigDecimal ejercicio, String activo, Set<Contador> contadors) {
       this.idejercicio = idejercicio;
       this.ejercicio = ejercicio;
       this.activo = activo;
       this.contadors = contadors;
    }
   
    public BigDecimal getIdejercicio() {
        return this.idejercicio;
    }
    
    public void setIdejercicio(BigDecimal idejercicio) {
        this.idejercicio = idejercicio;
    }
    public BigDecimal getEjercicio() {
        return this.ejercicio;
    }
    
    public void setEjercicio(BigDecimal ejercicio) {
        this.ejercicio = ejercicio;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<Contador> getContadors() {
        return this.contadors;
    }
    
    public void setContadors(Set<Contador> contadors) {
        this.contadors = contadors;
    }




}


