--------------------------------------------------------
-- Archivo creado  - viernes-noviembre-08-2013   
--------------------------------------------------------
  DROP TABLE "MAESTROS"."CLIENTE" cascade constraints;
  DROP TABLE "MAESTROS"."CONTADOR" cascade constraints;
  DROP TABLE "MAESTROS"."EJERCICIO" cascade constraints;
  DROP TABLE "MAESTROS"."ESTADOS" cascade constraints;
  DROP TABLE "MAESTROS"."PERITO" cascade constraints;
  DROP TABLE "MAESTROS"."SERIES" cascade constraints;
  
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "MAESTROS"."CLIENTE" 
   (	"IDCLIENTE" NUMBER, 
	"IDPOBLACION" VARCHAR2(4 BYTE), 
	"IDSERIE" NUMBER, 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"SOLICITANTE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"PAGADOR" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CABECERAFAC" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CABECERAINF" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CIF" VARCHAR2(9 BYTE), 
	"DIRECCION" VARCHAR2(150 BYTE), 
	"CODIGO_POSTAL" NUMBER, 
	"WEB" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TELEFONO1" VARCHAR2(50 BYTE), 
	"TELEFONO2" VARCHAR2(50 BYTE), 
	"FAX" VARCHAR2(20 BYTE), 
	"PERSONA_CONTACTO" VARCHAR2(50 BYTE), 
	"COMENTARIO" VARCHAR2(150 BYTE), 
	"BAJA" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"IRPF" NUMBER, 
	"IVA" NUMBER, 
	"FECHA_ALTA" DATE, 
	"CUENTA_CONTABLE" VARCHAR2(30 BYTE), 
	"IDPROVINCIA" VARCHAR2(2 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON TABLE "MAESTROS"."CLIENTE"  IS 'TABLA DE CLIENTES.
EN ELLA ESTAN ASOCIADAS EL NOMBRE DEL CLIENTE, EL TIPO DE FACTURACION (ESTE TIPO VIENE DE LA TABLA DE TEXTOS COMUNES SUBTXT DONDE SE VA A ALMACENAR EL SUBCODIGO DE LA TABLA, PARA EL TIPO DE FACTURACION EL CODIGO DE TEXTOS COMUNES QUE LE CORRESPONDE ES EL 1).
FK: TIENE ASOCIADO EL ID DE LA POBLACION A LA QUE PERTENECE Y LA SERIE DE FACTURACION';
--------------------------------------------------------
--  DDL for Table EJERCICIO
--------------------------------------------------------

  CREATE TABLE "MAESTROS"."EJERCICIO" 
   (	"IDEJERCICIO" NUMBER, 
	"EJERCICIO" NUMBER, 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "MAESTROS"."EJERCICIO"."IDEJERCICIO" IS 'PK DEL EJERCICIO';
 
   COMMENT ON COLUMN "MAESTROS"."EJERCICIO"."EJERCICIO" IS 'IDENTIFICA EL NUMERO DEL EJERCICIO POR EJEMPLO 2013';
 
   COMMENT ON COLUMN "MAESTROS"."EJERCICIO"."ACTIVO" IS 'VALOR POR DEFECTO SI LA SERIE EST� ACTIVA
';
--------------------------------------------------------
--  DDL for Table SERIES
--------------------------------------------------------

  CREATE TABLE "MAESTROS"."SERIES" 
   (	"IDSERIE" NUMBER, 
	"CODIGO" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(60 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "MAESTROS"."SERIES"."IDSERIE" IS 'PK DE LA SERIE';
 
   COMMENT ON COLUMN "MAESTROS"."SERIES"."CODIGO" IS 'POR EJEMPLO PTR';
 
   COMMENT ON COLUMN "MAESTROS"."SERIES"."DESCRIPCION" IS 'DESCRIPCION DE LA SERIE';
--------------------------------------------------------
--  DDL for Table CONTADOR
--------------------------------------------------------

  CREATE TABLE "MAESTROS"."CONTADOR" 
   (	"IDSERIE" NUMBER, 
	"IDEJERCICIO" NUMBER, 
	"CONTADOR" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERITO
--------------------------------------------------------

  CREATE TABLE "MAESTROS"."PERITO" 
   (	"IDPERITO" NUMBER, 
	"PERITO" VARCHAR2(150 BYTE), 
	"CODIGO_POSTAL" VARCHAR2(5 BYTE), 
	"TELEFONO1" VARCHAR2(15 BYTE), 
	"TELEFONO2" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"COMENTARIO" VARCHAR2(512 BYTE), 
	"NIF" VARCHAR2(20 BYTE), 
	"IRPF" NUMBER, 
	"IVA" NUMBER, 
	"RESULTANTE" NUMBER, 
	"FIJO" NUMBER, 
	"PRECIO_KM" NUMBER, 
	"COCHE_PROPIO" VARCHAR2(1 BYTE), 
	"FOTOS" VARCHAR2(1 BYTE), 
	"FECHA_ALTA" DATE, 
	"BAJA" VARCHAR2(1 BYTE), 
	"IDPOBLACION" VARCHAR2(4 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;

---------------------------------------------------
--   DATA FOR TABLE CONTADOR
--   FILTER = none used
---------------------------------------------------
REM INSERTING into MAESTROS.CONTADOR

---------------------------------------------------
--   END DATA FOR TABLE CONTADOR
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE SERIES
--   FILTER = none used
---------------------------------------------------
REM INSERTING into MAESTROS.SERIES

---------------------------------------------------
--   END DATA FOR TABLE SERIES
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE EJERCICIO
--   FILTER = none used
---------------------------------------------------
REM INSERTING into MAESTROS.EJERCICIO
Insert into MAESTROS.EJERCICIO (IDEJERCICIO,EJERCICIO,ACTIVO) values (1,2012,'N');
Insert into MAESTROS.EJERCICIO (IDEJERCICIO,EJERCICIO,ACTIVO) values (2,2013,'S');
Insert into MAESTROS.EJERCICIO (IDEJERCICIO,EJERCICIO,ACTIVO) values (3,2014,'N');
Insert into MAESTROS.EJERCICIO (IDEJERCICIO,EJERCICIO,ACTIVO) values (4,2015,'N');
Insert into MAESTROS.EJERCICIO (IDEJERCICIO,EJERCICIO,ACTIVO) values (5,2016,'N');
Insert into MAESTROS.EJERCICIO (IDEJERCICIO,EJERCICIO,ACTIVO) values (6,2017,'N');
Insert into MAESTROS.EJERCICIO (IDEJERCICIO,EJERCICIO,ACTIVO) values (7,2018,'N');

---------------------------------------------------
--   END DATA FOR TABLE EJERCICIO
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE CLIENTE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into MAESTROS.CLIENTE
Insert into MAESTROS.CLIENTE (IDCLIENTE,IDPOBLACION,IDSERIE,NOMBRE,SOLICITANTE,PAGADOR,CABECERAFAC,CABECERAINF,CIF,DIRECCION,CODIGO_POSTAL,WEB,EMAIL,TELEFONO1,TELEFONO2,FAX,PERSONA_CONTACTO,COMENTARIO,BAJA,IRPF,IVA,FECHA_ALTA,CUENTA_CONTABLE,IDPROVINCIA) values (1,'1',1,'clienteMaestros1','S','S','S','S','6',null,4,'d','d','4','6','4','44','4','A',5,5,to_timestamp('12/12/12 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'1','1');
Insert into MAESTROS.CLIENTE (IDCLIENTE,IDPOBLACION,IDSERIE,NOMBRE,SOLICITANTE,PAGADOR,CABECERAFAC,CABECERAINF,CIF,DIRECCION,CODIGO_POSTAL,WEB,EMAIL,TELEFONO1,TELEFONO2,FAX,PERSONA_CONTACTO,COMENTARIO,BAJA,IRPF,IVA,FECHA_ALTA,CUENTA_CONTABLE,IDPROVINCIA) values (2,'1',1,'cliente2','S','S','S','S','6',null,4,'d','d','4','6','4','44','4','A',5,5,to_timestamp('12/12/12 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'1','1');
Insert into MAESTROS.CLIENTE (IDCLIENTE,IDPOBLACION,IDSERIE,NOMBRE,SOLICITANTE,PAGADOR,CABECERAFAC,CABECERAINF,CIF,DIRECCION,CODIGO_POSTAL,WEB,EMAIL,TELEFONO1,TELEFONO2,FAX,PERSONA_CONTACTO,COMENTARIO,BAJA,IRPF,IVA,FECHA_ALTA,CUENTA_CONTABLE,IDPROVINCIA) values (4,'1',1,'cliente4','S','S','S','S','6',null,4,'d','d','4','6','4','44','4','A',5,5,to_timestamp('12/12/12 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'1','1');
Insert into MAESTROS.CLIENTE (IDCLIENTE,IDPOBLACION,IDSERIE,NOMBRE,SOLICITANTE,PAGADOR,CABECERAFAC,CABECERAINF,CIF,DIRECCION,CODIGO_POSTAL,WEB,EMAIL,TELEFONO1,TELEFONO2,FAX,PERSONA_CONTACTO,COMENTARIO,BAJA,IRPF,IVA,FECHA_ALTA,CUENTA_CONTABLE,IDPROVINCIA) values (3,'1',1,'cliente3','S','S','S','S','6',null,4,'d','d','4','6','4','44','4','A',5,5,to_timestamp('12/12/12 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'1','1');

---------------------------------------------------
--   END DATA FOR TABLE CLIENTE
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PERITO
--   FILTER = none used
---------------------------------------------------
REM INSERTING into MAESTROS.PERITO
Insert into MAESTROS.PERITO (IDPERITO,PERITO,CODIGO_POSTAL,TELEFONO1,TELEFONO2,EMAIL,COMENTARIO,NIF,IRPF,IVA,RESULTANTE,FIJO,PRECIO_KM,COCHE_PROPIO,FOTOS,FECHA_ALTA,BAJA,IDPOBLACION) values (1,'PERITO1','30120','123','123',null,null,null,null,null,null,null,null,null,null,null,null,'1');
Insert into MAESTROS.PERITO (IDPERITO,PERITO,CODIGO_POSTAL,TELEFONO1,TELEFONO2,EMAIL,COMENTARIO,NIF,IRPF,IVA,RESULTANTE,FIJO,PRECIO_KM,COCHE_PROPIO,FOTOS,FECHA_ALTA,BAJA,IDPOBLACION) values (2,'PERITO2','30120','123','123',null,null,null,null,null,null,null,null,null,null,null,null,'1');
Insert into MAESTROS.PERITO (IDPERITO,PERITO,CODIGO_POSTAL,TELEFONO1,TELEFONO2,EMAIL,COMENTARIO,NIF,IRPF,IVA,RESULTANTE,FIJO,PRECIO_KM,COCHE_PROPIO,FOTOS,FECHA_ALTA,BAJA,IDPOBLACION) values (3,'PERITO3','30120','123','123',null,null,null,null,null,null,null,null,null,null,null,null,'1');

---------------------------------------------------
--   END DATA FOR TABLE PERITO
---------------------------------------------------
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "MAESTROS"."CLIENTE" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."CLIENTE" MODIFY ("IDPOBLACION" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."CLIENTE" MODIFY ("IDSERIE" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."CLIENTE" MODIFY ("IDPROVINCIA" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."CLIENTE" ADD PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTADOR
--------------------------------------------------------

  ALTER TABLE "MAESTROS"."CONTADOR" MODIFY ("IDSERIE" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."CONTADOR" MODIFY ("IDEJERCICIO" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."CONTADOR" MODIFY ("CONTADOR" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."CONTADOR" ADD PRIMARY KEY ("IDSERIE", "IDEJERCICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EJERCICIO
--------------------------------------------------------

  ALTER TABLE "MAESTROS"."EJERCICIO" MODIFY ("IDEJERCICIO" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."EJERCICIO" ADD PRIMARY KEY ("IDEJERCICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERITO
--------------------------------------------------------

  ALTER TABLE "MAESTROS"."PERITO" MODIFY ("IDPERITO" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."PERITO" MODIFY ("IDPOBLACION" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."PERITO" ADD PRIMARY KEY ("IDPERITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERIES
--------------------------------------------------------

  ALTER TABLE "MAESTROS"."SERIES" MODIFY ("IDSERIE" NOT NULL ENABLE);
 
  ALTER TABLE "MAESTROS"."SERIES" ADD PRIMARY KEY ("IDSERIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  DDL for Index SYS_C004166
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTROS"."SYS_C004166" ON "MAESTROS"."CLIENTE" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005025
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTROS"."SYS_C005025" ON "MAESTROS"."CONTADOR" ("IDSERIE", "IDEJERCICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005021
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTROS"."SYS_C005021" ON "MAESTROS"."EJERCICIO" ("IDEJERCICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004169
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTROS"."SYS_C004169" ON "MAESTROS"."PERITO" ("IDPERITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005019
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTROS"."SYS_C005019" ON "MAESTROS"."SERIES" ("IDSERIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "MAESTROS"."SYS_C004169" ON "MAESTROS"."PERITO" ("IDPERITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005019
--------------------------------------------------------

  ALTER TABLE "MAESTROS"."CONTADOR" ADD FOREIGN KEY ("IDSERIE")
	  REFERENCES "MAESTROS"."SERIES" ("IDSERIE") ENABLE;
 
  ALTER TABLE "MAESTROS"."CONTADOR" ADD FOREIGN KEY ("IDEJERCICIO")
	  REFERENCES "MAESTROS"."EJERCICIO" ("IDEJERCICIO") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table CONTADOR
--------------------------------------------------------

  ALTER TABLE "MAESTROS"."CONTADOR" ADD FOREIGN KEY ("IDSERIE")
	  REFERENCES "MAESTROS"."SERIES" ("IDSERIE") ENABLE;
 
  ALTER TABLE "MAESTROS"."CONTADOR" ADD FOREIGN KEY ("IDEJERCICIO")
	  REFERENCES "MAESTROS"."EJERCICIO" ("IDEJERCICIO") ENABLE;

